name: CI-CD Protection Pipeline

on:
  push:
    branches: ["main"]

jobs:
  bash-lint:
    runs-on: [self-hosted, linux, shell, dev]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Bash Scripts
        run: |
          chmod +x deploy.sh
          shellcheck deploy.sh

  yaml-lint:
    runs-on: [self-hosted, linux, shell, dev]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint YAML Configuration
        run: yamllint .

  python-unit-test:
    runs-on: [self-hosted, linux, shell, dev]
    needs: [bash-lint, yaml-lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python Unit Tests
        run: python3 -m pytest test_app.py
